### ISSUE TITLE
Lodash vs Sift.js

### ISSUE THREAD

**Issue by jdnichollsc** [crcn/sift.js#115] opened 2017-01-16 21:42 UTC
Hi guys,

**Lodash** return an element but **Sift.js** return an empty Array, check please [here](https://gist.github.com/jdnichollsc/00ea8cf1204b17d9fb9a991fbd1dfee6)

Thanks in advance, Nicholls

**Comment by crcn** [comment] 2017-04-11 19:24
I wasn't able to reproduce this with a test: https://github.com/crcn/sift.js/blob/master/test/basic-test.js#L123. Could it be a sift version mismatch?

**Comment by swordfish444** [comment] 2017-07-08 18:15
@jdnichollsc I reviewed your sift query and it's working correctly. Both start dates are 1/13/2017 which is > period.startDate. Hard to compare your custom lodash filter fn with the sift example tbh.

**Comment by crcn** [comment] 2017-07-17 12:50
Thanks for checking this out @swordfish444. I'm closing this ticket since it's months old and cannot be reproduced.

**Closed by crcn** 2017-07-17 12:50 UTC
Labels: cannot reproduce
