### ISSUE TITLE
Error: "Cannot nest $ under $in" when querying Mongo IDs

### ISSUE THREAD

**Issue by zachsa** [crcn/sift.js#231] opened 2021-08-05 07:01 UTC
Hi,

I use this library in conjunction with the DataLoader library (like many others I'm sure).  I have a batching function that takes a number of filters, runs a single query on mongo, and then uses sift to 'unbatch' the results

```
filters = [
  {},
  {$in: [...]},
  etc
]

// Batch for Mongo
query = {$or: filters}
docs = mongo.find(query)

// 'Unbatch' using sift
filter1Results = docs.filter(sift(filter1))
filter2Results = docs.filter(sift(filter2))
etc
```

In other words I'm using the same filter to find Mongo documents as for filtering a JavaScript array using sift. This worked with versions prior 14 despite that sift needed to match objects to objects (auto-generated _ids in Mongo).

Since updating to v14 my batching functions fail.

**v13.5.4**
This works
```js
docs.filter(sift({ _id: { '$in': [ new ObjectId("610b6bc9e29dbd1bb5f045bf") ] } }))
```

In `v14.02`, for the same expression sift throws an error:
```
cannot nest $ under $in
```

**Comment by crcn** [comment] 2021-08-06 14:25
Hmmm, I'm having a hard time reproducing this. Do you have an example snippet that breaks? Here's what I'm using:

```javascript
const test = sift({ _id: { '$in': [ new ObjectID("610b6bc9e29dbd1bb5f045bf") ] } })
assert.equal(test({ _id: new ObjectID("610b6bc9e29dbd1bb5f045bf") }), true);  
```

**Comment by zachsa** [comment] 2021-08-06 14:40
Hi,

The snippet I added above:

```
docs.filter(sift({ _id: { '$in': [ new ObjectId("610b6bc9e29dbd1bb5f045bf") ] } }))
```

- I'm not actually calling `new ObjectId(...)`. This is the output to the console when logging a MongoID. i.e. the _id returned from `collection.find({})` (sorry, I could have made this clearer)
- I'm using the Node.js Mongo client (https://www.npmjs.com/package/mongodb) v4.1
- MongoDB 4.4.3

**Comment by eric-swann-q2** [comment] 2021-09-19 15:12
Ran into the same issue.... What I"m seeing is that this method fails because it's looking at object "proto" properties, thus finding a match on "toString" which exists in both. 
`    var containsOperation = function (query, options) {
        for (var key in query) { //This isn't just cycling the $operations, it's also including _proto_ props, thus finding a match.
            if (if options.operations[key])
                return true;
        }
        return false;
    };
`

Have you considered using the following ? I think that would eliminate the issue I'm seeing at least.
`
var containsOperation = function (query, options) {
        for (var key in query) {
            if (options.operations.hasOwnProperty(key)) // Test for hasOwnProperty here instead of just a regular key comparison
                return true;
        }
        return false;
    };
`

**Comment by crcn** [comment] 2021-09-24 14:08
Thanks for the suggestion! This should be up on NPM as `sift@14.0.3`. Let me know if that fixes the issue.

**Comment by crcn** [comment] 2021-11-18 14:05
Closing since this should be fixed now.

**Closed by crcn** 2021-11-18 14:05 UTC
Labels: bug
